# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choiceScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from jointType import Ui_jointWindow
from jointType2 import Ui_jointWindow2
from jointType3 import Ui_jointWindow3

class Ui_choiceScreen(object):
    def openWindow(self,screen,mainWindow):
        self.window=QtWidgets.QMainWindow()

        if(screen=='1'):
            self.ui=Ui_jointWindow()
        elif(screen=='2'):
            self.ui=Ui_jointWindow2()
        elif(screen=='3'):
            self.ui=Ui_jointWindow3()
        self.ui.setupUi(self.window)
        self.window.show()
        mainWindow.hide()

    def setupUi(self, Window2):
        Window2.setObjectName("Window2")
        Window2.resize(580, 504)
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        Window2.setFont(font)
        Window2.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(Window2)
        self.centralwidget.setObjectName("centralwidget")
        self.fKButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda:self.openWindow('1',Window2))
        self.fKButton.setGeometry(QtCore.QRect(210, 130, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(12)
        self.fKButton.setFont(font)
        self.fKButton.setStyleSheet("background-color: rgb(254, 233, 226);")
        self.fKButton.setObjectName("fKButton")
        self.iKButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda:self.openWindow('2',Window2))
        self.iKButton.setGeometry(QtCore.QRect(210, 220, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(12)
        self.iKButton.setFont(font)
        self.iKButton.setStyleSheet("background-color: rgb(215, 228, 253);")
        self.iKButton.setObjectName("iKButton")
        self.pPButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda:self.openWindow('3',Window2))
        self.pPButton.setGeometry(QtCore.QRect(210, 310, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(12)
        self.pPButton.setFont(font)
        self.pPButton.setStyleSheet("background-color: rgb(222, 201, 254);")
        self.pPButton.setObjectName("pPButton")
        Window2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Window2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 573, 21))
        self.menubar.setObjectName("menubar")
        Window2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Window2)
        self.statusbar.setObjectName("statusbar")
        Window2.setStatusBar(self.statusbar)

        self.retranslateUi(Window2)
        QtCore.QMetaObject.connectSlotsByName(Window2)

    def retranslateUi(self, Window2):
        _translate = QtCore.QCoreApplication.translate
        Window2.setWindowTitle(_translate("Window2", "Robotics Project"))
        self.fKButton.setText(_translate("Window2", "Forward Kinematics"))
        self.iKButton.setText(_translate("Window2", "Inverse Kinematics"))
        self.pPButton.setText(_translate("Window2", "Path Planning "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Window2 = QtWidgets.QMainWindow()
    ui = Ui_choiceScreen()
    ui.setupUi(Window2)
    Window2.show()
    sys.exit(app.exec_())
