# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dhWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from fKandJ import Ui_fkandJWindow

import sys
sys.path.insert(0, '../')
from robot import setDHParameter

class Ui_MainWindow(object):
    dhMatrix=[]
    def __init__(self,joints,jointNumber):
        self.joints=joints
        self.jointNumber=jointNumber

    def openWindow(self,mainWindow):
#         for i in range(self.jointNumber):
#             for j in  range(4):
#                 print(self.dhMatrix[i][j].toPlainText())
        self.dhMatrix=setDHParameter(self.dhMatrix)
        
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_fkandJWindow(self.joints,self.dhMatrix)
        self.ui.setupUi(self.window)
        self.window.show()
        mainWindow.hide()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(580, 504)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(15)
        
        self.aTextField = QtWidgets.QLabel(self.centralwidget)
        self.aTextField.setGeometry(QtCore.QRect(200, 50, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(15)
        self.aTextField.setFont(font)
        self.aTextField.setObjectName("aTextField")
        self.alphaTextField = QtWidgets.QLabel(self.centralwidget)
        self.alphaTextField.setGeometry(QtCore.QRect(270, 40, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(15)
        self.alphaTextField.setFont(font)
        self.alphaTextField.setObjectName("alphaTextField")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(390, 40, 21, 51))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(470, 40, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        for i in range(self.jointNumber):
            dh=[]
            self.label = QtWidgets.QLabel(self.centralwidget)
            self.label.setGeometry(QtCore.QRect(30, 80+i*50, 110, 41))
            self.label.setFont(font)
            self.label.setObjectName("label")
            self.label.setText('For joint '+str(i+1))
            self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
            self.textEdit.setGeometry(QtCore.QRect(190, 90+i*50, 31, 31))
            self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
            self.textEdit.setObjectName("textEdit")
            self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
            self.textEdit_2.setGeometry(QtCore.QRect(280, 90+i*50, 31, 31))
            self.textEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
            self.textEdit_2.setObjectName("textEdit_2")
            self.dTextField = QtWidgets.QTextEdit(self.centralwidget)
            self.dTextField.setGeometry(QtCore.QRect(380, 90+i*50, 31, 31))
            self.dTextField.setStyleSheet("background-color: rgb(255, 255, 255);")
            self.dTextField.setObjectName("dTextField")
            self.thetaTextField = QtWidgets.QTextEdit(self.centralwidget)
            self.thetaTextField.setGeometry(QtCore.QRect(480, 90+i*50, 31, 31))
            self.thetaTextField.setStyleSheet("background-color: rgb(255, 255, 255);")
            self.thetaTextField.setObjectName("thetaTextField")

            dh.append(self.textEdit)
            dh.append(self.textEdit_2)
            dh.append(self.dTextField)
            dh.append(self.thetaTextField)
            self.dhMatrix.append(dh)

        self.next_2 = QtWidgets.QPushButton(self.centralwidget,clicked= lambda:self.openWindow(MainWindow))
        self.next_2.setGeometry(QtCore.QRect(470, 420, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.next_2.setFont(font)
        self.next_2.setStyleSheet("background-color: rgb(215, 228, 253);")
        self.next_2.setObjectName("next_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 583, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Robotics Project"))
        # self.label.setText(_translate("MainWindow", "For joint "))
        self.aTextField.setText(_translate("MainWindow", "a"))
        self.alphaTextField.setText(_translate("MainWindow", "Alpha"))
        self.label_4.setText(_translate("MainWindow", "d"))
        self.label_5.setText(_translate("MainWindow", "Theta"))
        self.next_2.setText(_translate("MainWindow", "Next"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
