# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jacobian&fK.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import sys
sys.path.insert(0, '../')
from robot import fK,getJacobian
# import choiceScreen 
# # from choiceScreen import Ui_choiceScreen
class Ui_fkandJWindow(object):
    
    def __init__(self,joints,dhMatrix):
        self.list_TF,self.x,self.y,self.z,self.roll,self.pitch,self.yaw= fK(dhMatrix)
        print(self.list_TF,self.x,self.y,self.z)
        self.joints=joints
        self.jacobian_matrix=getJacobian(joints,self.list_TF)
        # print(self.jacobian_matrix)
        

    def backToStart(self,mainWindow):
        self.window=QtWidgets.QMainWindow()
        self.ui=choiceScreen.Ui_choiceScreen()
        self.ui.setupUi(self.window)
        self.window.show()
        mainWindow.hide()
        

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(580, 504)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.back = QtWidgets.QPushButton(self.centralwidget,clicked= lambda:self.backToStart(MainWindow))
        self.back.setGeometry(QtCore.QRect(10, 420, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.back.setFont(font)
        self.back.setStyleSheet("background-color: rgb(222, 201, 254);")
        self.back.setObjectName("back")
        
        
        self.printText = QtWidgets.QLabel(self.centralwidget)
        self.printText.setGeometry(QtCore.QRect(10, 80, 371, 91))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(16)
        self.printText.setFont(font)
        self.printText.setObjectName("printText")
        self.xLabel = QtWidgets.QLabel(self.centralwidget)
        self.xLabel.setGeometry(QtCore.QRect(120, 170, 47, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(14)
        self.xLabel.setFont(font)
        self.xLabel.setObjectName("xLabel")
        self.yLabel = QtWidgets.QLabel(self.centralwidget)
        self.yLabel.setGeometry(QtCore.QRect(120, 210, 47, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(14)
        self.yLabel.setFont(font)
        self.yLabel.setObjectName("yLabel")
        self.zLabel = QtWidgets.QLabel(self.centralwidget)
        self.zLabel.setGeometry(QtCore.QRect(120, 250, 47, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(14)
        self.zLabel.setFont(font)
        self.zLabel.setObjectName("zLabel")
        self.rollLabel = QtWidgets.QLabel(self.centralwidget)
        self.rollLabel.setGeometry(QtCore.QRect(350, 170, 47, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(14)
        self.rollLabel.setFont(font)
        self.rollLabel.setObjectName("rollLabel")
        self.pitchLabel = QtWidgets.QLabel(self.centralwidget)
        self.pitchLabel.setGeometry(QtCore.QRect(350, 210, 47, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(14)
        self.pitchLabel.setFont(font)
        self.pitchLabel.setObjectName("pitchLabel")
        self.yawLabel = QtWidgets.QLabel(self.centralwidget)
        self.yawLabel.setGeometry(QtCore.QRect(350, 250, 47, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(14)
        self.yawLabel.setFont(font)
        self.yawLabel.setObjectName("yawLabel")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(160, 170, 71, 31))
        
        
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(160, 210, 71, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(160, 250, 71, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(410, 170, 71, 31))
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_5.setGeometry(QtCore.QRect(410, 210, 71, 31))
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_6.setGeometry(QtCore.QRect(410, 250, 71, 31))
        self.textEdit_6.setObjectName("textEdit_6")
        # self.printText_2 = QtWidgets.QLabel(self.centralwidget)
        # self.printText_2.setGeometry(QtCore.QRect(10, 150, 371, 91))
        
        # Print 
        self.textEdit.setText(str(round(self.x,1)))
        self.textEdit_2.setText(str(round(self.y,1)))
        self.textEdit_3.setText(str(round(self.z,1))) 
        self.textEdit_4.setText(str(round(self.roll,1)))
        self.textEdit_5.setText(str(round(self.pitch,1)))
        self.textEdit_6.setText(str(round(self.yaw,1)))
        
# Print jacobian
        
#         font = QtGui.QFont()
#         font.setFamily("Sitka")
#         font.setPointSize(16)
#         self.printText_2.setFont(font)
#         self.printText_2.setObjectName("printText_2")
        
#         font = QtGui.QFont()
#         font.setFamily("Sitka")
#         font.setPointSize(16)
#         self.textEdit_7 = QtWidgets.QTextEdit(self.centralwidget)
#         self.textEdit_7.setGeometry(QtCore.QRect(70, 210, 440, 200))
#         self.textEdit_7.setFont(font)
#         self.textEdit_7.setObjectName("textEdit")
#         self.textEdit_7.setText(str(self.jacobian_matrix))
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 587, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Robotics Project"))
        self.back.setText(_translate("MainWindow", "Exit"))
        self.printText.setText(_translate("MainWindow", "The End Effector Pose is"))
        self.xLabel.setText(_translate("MainWindow", "X"))
        self.yLabel.setText(_translate("MainWindow", "Y"))
        self.zLabel.setText(_translate("MainWindow", "Z"))
        self.rollLabel.setText(_translate("MainWindow", "Roll"))
        self.pitchLabel.setText(_translate("MainWindow", "Pitch"))
        self.yawLabel.setText(_translate("MainWindow", "Yaw"))
        # self.printText_2.setText(_translate("MainWindow", "Jacobian Matrix"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
