# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jacobian&fK.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import sys
sys.path.insert(0, '../')
from robot import fK,getJacobian,inv_jacobian
# import choiceScreen 
# # from choiceScreen import Ui_choiceScreen
class Ui_fkandJWindow(object):
    
    def __init__(self,joints,dhMatrix):
        self.list_TF,self.x,self.y,self.z,self.roll,self.pitch,self.yaw= fK(dhMatrix)
        print(self.list_TF,self.x,self.y,self.z)
        self.joints=joints
        self.jacobian_matrix=getJacobian(joints,self.list_TF)
        self.inverse_jacobian=inv_jacobian(self.jacobian_matrix)
        # print(self.jacobian_matrix)
        

    def backToStart(self,mainWindow):
        self.window=QtWidgets.QMainWindow()
        self.ui=choiceScreen.Ui_choiceScreen()
        self.ui.setupUi(self.window)
        self.window.show()
        mainWindow.hide()
        

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(580, 504)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # self.back = QtWidgets.QPushButton(self.centralwidget,clicked= lambda:self.backToStart(MainWindow))
        # self.back.setGeometry(QtCore.QRect(10, 420, 91, 41))
        # font = QtGui.QFont()
        # font.setPointSize(14)
        # self.back.setFont(font)
        # self.back.setStyleSheet("background-color: rgb(222, 201, 254);")
        # self.back.setObjectName("back")
        
        # Print 
        self.printText = QtWidgets.QLabel(self.centralwidget)
        self.printText.setGeometry(QtCore.QRect(10, -30, 371, 91))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(16)
        self.printText.setFont(font)
        self.printText.setObjectName("printText")
        
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(16)
        self.textEdit_7 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_7.setGeometry(QtCore.QRect(70, 40, 440, 200))
        self.textEdit_7.setFont(font)
        self.textEdit_7.setObjectName("textEdit")
        self.textEdit_7.setText(str(self.jacobian_matrix))
        
        self.printText_2 = QtWidgets.QLabel(self.centralwidget)
        self.printText_2.setGeometry(QtCore.QRect(10, 210, 371, 91))
        
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(16)
        self.printText_2.setFont(font)
        self.printText_2.setObjectName("printText_2")
        
        
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(16)
        self.textEdit_8 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_8.setGeometry(QtCore.QRect(70, 280, 440, 200))
        self.textEdit_8.setFont(font)
        self.textEdit_8.setObjectName("textEdit")
        self.textEdit_8.setText(str(self.inverse_jacobian))

        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 587, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Robotics Project"))
        # self.back.setText(_translate("MainWindow", "Exit"))
        self.printText.setText(_translate("MainWindow","Jacobian Forward Matrix"))
        self.printText_2.setText(_translate("MainWindow", "Jacobian Inverse Matrix"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
