# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pPPrint.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import sys
sys.path.insert(0, '../')
from robot import get_trajectory

class Ui_pPPrint(object):
    
    def __init__ (self,joints,dhMatrix,to,tf):
        to=to.toPlainText()
        to=float(to)
        tf=tf.toPlainText()
        tf=float(tf)
        self.jointsEquations=get_trajectory(dhMatrix,joints,initialTime = to, finalTime = tf)
        print(self.jointsEquations)
        
    def backToStart(self,mainWindow):
        self.window=QtWidgets.QMainWindow()
        # self.ui=Ui_choiceScreen()
        self.ui.setupUi(self.window)
        self.window.show()
        mainWindow.hide()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(580, 504)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.back = QtWidgets.QPushButton(self.centralwidget,clicked= lambda:self.backToStart(MainWindow))
        self.back.setGeometry(QtCore.QRect(10, 420, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.back.setFont(font)
        self.back.setStyleSheet("background-color: rgb(222, 201, 254);")
        self.back.setObjectName("back")
        #print
        self.printText = QtWidgets.QLabel(self.centralwidget)
        self.printText.setGeometry(QtCore.QRect(20, 0, 371, 91))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(16)
        self.printText.setFont(font)
        self.printText.setObjectName("printText")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(16)
        self.textEdit.setFont(font)
        self.textEdit.setGeometry(QtCore.QRect(40, 100, 521, 231))
        self.textEdit.setObjectName("textEdit")
        self.textEdit.setText(str(self.jointsEquations))
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 617, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Robotics Project"))
        self.back.setText(_translate("MainWindow", "Exit"))
        self.printText.setText(_translate("MainWindow", "Joint Trajectories"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_pPPrint()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
