# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pPWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pPPrint import Ui_pPPrint


class Ui_MainWindow(object):
    to=''
    tf=''
    
    def __init__(self,joints,dhMatrix):
        self.joints=joints
        self.dhMatrix=dhMatrix
    
    def openWindow(self):
        to=self.toField.toPlainText()
        tf=self.tfField.toPlainText()
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_pPPrint(self.joints,self.dhMatrix,self.to,self.tf)
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(580, 504)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.toField = QtWidgets.QTextEdit(self.centralwidget)
        self.toField.setGeometry(QtCore.QRect(340, 140, 61, 31))
        self.toField.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.toField.setObjectName("toField")
        self.tfField = QtWidgets.QTextEdit(self.centralwidget)
        self.tfField.setGeometry(QtCore.QRect(340, 200, 61, 31))
        self.tfField.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tfField.setObjectName("tfField")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(190, 140, 61, 31))
        self.textEdit.setStyleSheet("background-color: rgb(215, 228, 253);")
        self.textEdit.setObjectName("textEdit")
        self.aTextField = QtWidgets.QLabel(self.centralwidget)
        self.aTextField.setGeometry(QtCore.QRect(210, 140, 20, 20))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(15)
        self.aTextField.setFont(font)
        self.aTextField.setStyleSheet("background-color: rgb(215, 228, 253);")
        self.aTextField.setObjectName("aTextField")
        
        self.aTextField_2 = QtWidgets.QLabel(self.centralwidget)
        self.aTextField_2.setGeometry(QtCore.QRect(210, 200, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(15)
        self.aTextField_2.setFont(font)
        self.aTextField_2.setObjectName("aTextField_2")
        self.tfLabel = QtWidgets.QTextEdit(self.centralwidget)
        self.tfLabel.setGeometry(QtCore.QRect(190, 200, 61, 31))
        self.tfLabel.setStyleSheet("background-color: rgb(215, 228, 253);")
        self.tfLabel.setObjectName("tfLabel")
        self.aTextField_3 = QtWidgets.QLabel(self.centralwidget)
        self.aTextField_3.setGeometry(QtCore.QRect(210, 200, 16, 20))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(15)
        self.aTextField_3.setFont(font)
        self.aTextField_3.setStyleSheet("background-color: rgb(215, 228, 253);")
        self.aTextField_3.setObjectName("aTextField_3")
        self.nextButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda:self.openWindow())
        self.nextButton.setGeometry(QtCore.QRect(470, 420, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.nextButton.setFont(font)
        self.nextButton.setStyleSheet("background-color: rgb(215, 228, 253);")
        self.nextButton.setObjectName("nextButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 602, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Enter time interval"))
        self.aTextField.setText(_translate("MainWindow", "to"))
        self.aTextField_2.setText(_translate("MainWindow", "Y"))
        self.aTextField_3.setText(_translate("MainWindow", "tf"))
        self.nextButton.setText(_translate("MainWindow", "Next"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
